version: "3.9"

services: # Containers
  app:
    build: .
    volumes:
      - .:/HireX_3
    image: app:HireX_3

    command: python /HireX_3/manage.py runserver 0.0.0.0:8003
    ports:
    - 8003:8003
    depends_on:
    - db
    container_name: django_container

  db:
     image: postgres
     volumes:
       - ./data/db:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     container_name: postgres_db

volumes:
    postgres_data: